#Uncomment as needed
baseURL = "https://distsys-library.netlify.app/"
defaultContentLanguage = "en"
languageCode = "en-us"
Title = "Distributed Systems Library"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Miles Bryant"
# theme = "potato-dark"
theme = "papercss-hugo-theme"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"

  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  # twitter = "Your Twitter username"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  # github = "Your GitHub username"
  # gitlab = "Your GitLab username"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  # linkedin = "Your LinkedIn username"
  # # Disqus shortname
  # disqus = ""
  # # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"


[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
